       <footer class="footer-distributed">
        <div class="footer-logo">
            <img src="images/Newly-Webs.png" alt="logo" id="logo">
            <p class="footer-links">
                <a href="#">Home</a>
                |
                <a href="#">About</a>
                |
                <a href="#">Jobs</a>
            </p>
    
            <p class="footer-company-name">Copyright © 2024 <strong>Newly-Webs</strong> All rights reserved</p>
        </div>
    
        <div class="footer-center">
            <div>
                <img src="images/map-regular-36.png" alt="map-regular-36">
                <p>Ho Chi Minh City</p>
            </div>
    
            <div>
                <img src="images/phone-solid-36.png" alt="phone-solid-36">
                <p><a href="tel:+84779900990">+(84)779900990</a></p>
            </div>
            <div>
                <img class="bx-envelope" src="images/envelope-solid-36.png" alt="envelope-solid-36">
                <p><a href="images/Newly-webSP@gmail.com">Newly-webSP@gmail.com</a></p>
            </div>
        </div>
        <div class="footer-right">
            <p class="footer-company-about">
                <span>About the company</span>
                <strong>Empowering Your Digital Universe: Where Innovation Meets Technological Mastery with Newly-Webs</strong>. 
            </p>
            <div class="footer-icons">
                <a href="#"><img src="images/facebook-square-logo-36.png" alt="facebook-square-logo-36"></a>
                <a href="#"><img src="images/instagram-logo-36.png" alt="instagram-logo-36"></a>
                <a href="#"><img src="images/github-logo-36.png" alt="github-logo-36"></a>
                <a href="#"><img src="images/twitter-logo-36.png" alt="twitter-logo-36"></a>
                <a href="#"><img src="images/youtube-logo-36.png" alt="youtube-logo-36"></a>
            </div>
        </div>
    </footer>  