    <header class="main-header">
   
        <img id="teamlogo" src="images/Newly-Webs.png" alt="logo">
         <a href="#" class="header-logo">Newly-Webs </a>
    
     
       <input type="checkbox" id="checkA">
       <label for="checkA" class="icons-header">
         <i class="bx bx-menu" id="menu-icon"></i>
         <i class="bx bx-x" id="close-icon"></i>
       </label>
        
       <nav class="navbar">
         <a href="index.html" style="--i:0;" > HOME</a>
         <a href="about.html" style="--i:1;" class="active"> ABOUT US</a>
         <a href="apply.html" style="--i:2;" > APPLY</a>
         <a href="jobs.html" style="--i:3;"> JOB INFORMATION</a>
         <a href="enhancement.html" style="--i:4;"> ENHANCEMENT</a>
        </nav>
     
     
     </header>